Importação da base de dados
Analise exploratoria dos dados: Inicialmente a base de dados possuia uma virgula após a ultima coluna, para nosso codigo isso era interpretado como uma coluna sem nome, essa virgula foi removida para evitar problemas de columas sem nome com dados nulos.
O campo diagnosis é a variavel target que informa se possui a doença como M ou não B, a variável é do tipo string e será tratada mais adiante no processo.

In [1]:
import pandas as pd
dados = pd.read_csv("dados/dados.csv",sep=',')
#Mostrar primeiras linhas e na sequencia resumo de quantidade de linhas e colunas
print(dados.head())
print(dados.shape)

#exibe os valores de um campo
print(set(dados.radius_mean))

#resumo dos dados
print(dados.describe())

#lista tipo de dados da base
"""  campo diagnosis é do tipo string, precisará ser tratado, este campo sera nossa variavel 
target pois informa se a pessoa esta ou não doente

"""

print(dados.info())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0
1    842517         M        20.57         17.77          132.90     1326.0
2  84300903         M        19.69         21.25          130.00     1203.0
3  84348301         M        11.42         20.38           77.58      386.1
4  84358402         M        20.29         14.34          135.10     1297.0

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710
1          0.08474           0.07864          0.0869              0.07017
2          0.10960           0.15990          0.1974              0.12790
3          0.14250           0.28390          0.2414              0.10520
4          0.10030           0.13280          0.1980              0.10430

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0
1  ...         24.99          23.41           158.80      1956.0
2  ...         23.57          25.53           152.50      1709.0
3  ...         14.91          26.50            98.87       567.7
4  ...         22.54          16.67           152.20      1575.0

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654
1            0.1238             0.1866           0.2416                0.1860
2            0.1444             0.4245           0.4504                0.2430
3            0.2098             0.8663           0.6869                0.2575
4            0.1374             0.2050           0.4000                0.1625

   symmetry_worst  fractal_dimension_worst
0          0.4601                  0.11890
1          0.2750                  0.08902
2          0.3613                  0.08758
3          0.6638                  0.17300
4          0.2364                  0.07678

[5 rows x 32 columns]
(569, 32)
{6.981, 7.729, 8.196, 9.504, 10.95, 11.42, 12.45, 13.53, 13.73, 14.54, 14.68, 13.71, 13.0, 12.46, 16.02, 17.99, 18.25, 19.69, 20.57, 20.29, 19.17, 19.81, 21.16, 20.18, 25.22, 22.27, 24.25, 27.22, 28.11, 27.42, 9.738, 9.0, 9.268, 10.75, 10.25, 11.75, 11.5, 11.25, 12.0, 12.25, 12.75, 13.75, 13.5, 14.25, 14.5, 15.75, 15.0, 15.5, 16.78, 16.03, 16.5, 16.25, 17.47, 17.75, 18.22, 18.03, 19.0, 19.53, 20.47, 21.75, 8.726, 8.571, 9.72, 9.333, 10.44, 10.94, 10.97, 11.22, 11.47, 11.94, 11.69, 12.19, 12.47, 12.72, 12.94, 12.22, 13.44, 13.69, 13.47, 13.94, 14.44, 14.97, 14.22, 14.19, 14.69, 15.19, 14.47, 15.22, 9.029, 9.904, 10.66, 10.91, 10.16, 11.41, 11.66, 11.16, 12.91, 12.16, 13.66, 13.16, 14.41, 15.66, 16.13, 16.16, 16.69, 17.19, 17.91, 18.63, 18.94, 18.66, 19.16, 19.19, 19.44, 20.16, 20.94, 20.44, 20.13, 24.63, 8.618, 8.219, 9.606, 9.731, 9.755, 10.6, 10.88, 11.85, 11.6, 11.13, 11.63, 12.63, 12.1, 12.85, 12.88, 13.85, 13.88, 13.38, 14.6, 15.85, 15.1, 15.13, 8.671, 9.683, 10.57, 10.32, 10.82, 10.29, 11.29, 11.54, 11.32, 11.04, 11.57, 12.32, 12.54, 12.04, 12.07, 13.54, 13.82, 14.29, 14.04, 15.32, 15.04, 16.07, 16.35, 16.6, 17.57, 17.54, 17.35, 17.29, 17.6, 18.82, 17.85, 19.07, 19.1, 19.79, 20.6, 21.1, 23.29, 7.76, 9.397, 10.51, 10.26, 11.76, 11.26, 11.51, 12.76, 13.62, 13.01, 13.51, 14.26, 14.76, 8.95, 9.742, 10.2, 10.48, 11.95, 11.7, 11.45, 11.2, 12.98, 12.23, 12.95, 12.2, 12.7, 13.48, 13.45, 13.2, 13.98, 13.7, 14.48, 14.95, 14.45, 14.2, 15.7, 15.73, 16.26, 17.2, 17.95, 17.01, 18.45, 18.01, 19.45, 19.73, 20.26, 20.51, 20.48, 20.73, 20.2, 22.01, 23.51, 25.73, 9.777, 9.676, 9.295, 10.17, 11.67, 12.42, 12.67, 13.17, 14.42, 14.92, 8.878, 10.86, 11.89, 11.14, 11.64, 11.36, 11.61, 12.86, 12.36, 12.89, 12.39, 13.86, 13.64, 13.61, 13.11, 13.14, 14.64, 14.86, 14.61, 14.11, 15.61, 16.11, 16.17, 16.14, 17.14, 17.42, 17.08, 18.61, 18.08, 19.89, 20.58, 20.64, 20.92, 21.61, 8.598, 10.08, 11.08, 11.33, 12.83, 12.58, 13.08, 14.58, 15.08, 10.05, 10.8, 11.3, 11.52, 11.8, 11.27, 12.05, 12.77, 12.3, 12.8, 12.27, 13.05, 13.8, 13.27, 13.77, 13.3, 14.02, 14.8, 14.27, 14.05, 15.3, 15.27, 15.05, 16.24, 16.27, 16.74, 16.3, 17.3, 17.02, 17.05, 17.27, 18.77, 18.05, 18.49, 19.27, 19.02, 19.8, 19.55, 20.55, 23.27, 8.597, 8.734, 9.847, 10.49, 11.74, 11.99, 11.49, 12.49, 12.99, 13.49, 13.74, 13.24, 14.99, 14.74, 15.49, 9.567, 9.436, 9.668, 10.18, 10.71, 10.96, 11.93, 11.71, 11.43, 11.46, 11.68, 12.68, 12.18, 12.43, 12.21, 12.96, 13.43, 13.96, 13.46, 13.21, 13.68, 14.71, 14.96, 15.46, 15.71, 16.65, 16.46, 17.68, 17.46, 17.93, 18.65, 18.46, 19.21, 19.18, 19.4, 19.68, 21.71, 23.21, 8.888, 9.787, 9.876, 10.9, 10.65, 11.37, 11.9, 11.15, 11.87, 11.62, 12.87, 12.9, 12.62, 12.4, 12.65, 13.37, 13.15, 13.65, 13.87, 13.4, 14.62, 14.87, 14.9, 14.4, 13.9, 15.37, 15.12, 9.465, 11.84, 11.34, 12.34, 13.59, 13.34, 14.34, 14.59, 15.34, 16.84, 17.06, 18.81, 18.31, 19.59, 7.691, 20.31, 20.34, 20.09, 20.59, 21.09, 21.37, 21.56, 23.09, 9.042, 9.173, 9.405, 9.667, 9.423, 10.03, 11.06, 11.31, 11.28, 11.81, 12.03, 12.56, 12.78, 12.31, 12.06, 13.56, 13.81, 12.81, 13.03, 13.28, 14.03, 14.78, 14.06, 13.78, 14.53, 15.78, 15.06, 15.28, 15.53, 14.81}
                 id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000
mean          0.096360          0.104341        0.088799             0.048919
std           0.014064          0.052813        0.079720             0.038803
min           0.052630          0.019380        0.000000             0.000000
25%           0.086370          0.064920        0.029560             0.020310
50%           0.095870          0.092630        0.061540             0.033500
75%           0.105300          0.130400        0.130700             0.074000
max           0.163400          0.345400        0.426800             0.201200

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000
mean        0.181162  ...     16.269190      25.677223       107.261213
std         0.027414  ...      4.833242       6.146258        33.602542
min         0.106000  ...      7.930000      12.020000        50.410000
25%         0.161900  ...     13.010000      21.080000        84.110000
50%         0.179200  ...     14.970000      25.410000        97.660000
75%         0.195700  ...     18.790000      29.720000       125.400000
max         0.304000  ...     36.040000      49.540000       251.200000

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000
mean    880.583128          0.132369           0.254265         0.272188
std     569.356993          0.022832           0.157336         0.208624
min     185.200000          0.071170           0.027290         0.000000
25%     515.300000          0.116600           0.147200         0.114500
50%     686.500000          0.131300           0.211900         0.226700
75%    1084.000000          0.146000           0.339100         0.382900
max    4254.000000          0.222600           1.058000         1.252000

       concave points_worst  symmetry_worst  fractal_dimension_worst
count            569.000000      569.000000               569.000000
mean               0.114606        0.290076                 0.083946
std                0.065732        0.061867                 0.018061
min                0.000000        0.156500                 0.055040
25%                0.064930        0.250400                 0.071460
50%                0.099930        0.282200                 0.080040
75%                0.161400        0.317900                 0.092080
max                0.291000        0.663800                 0.207500

[8 rows x 31 columns]
<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 142.9 KB
None

Após analise visual importamos a bliblioteca missingno para fazer um double check e comprovar que não temos dados nulos na nossa base de dados

In [2]:
#importar bliblioteca para tratar dados nulos
import missingno as msno

#Exibe de forma grafica os dados nulos, novamente comprovando que o campo Unnamed esta somente com valores nulos
msno.matrix(dados)
# inicialmene a base de dados possuia o campo Unnamed com 569 registros nulos, 
#após essa verificação foi constatado a virgula adiconal após a ultima coluna
#essa virgula foi removida da base de dados e após nova execução nenhuma coluna possui dados nulos
print(dados.isnull().sum())

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

Comparação de variavies concave points_mean com diagnosis:
essa variavel possui uma correlação de 80% com nossa variavel target diagnosis, porém existem varios outlayers

In [3]:
import seaborn as sb
sb.boxplot(
    x="diagnosis",
    y="concave points_mean",
    hue="diagnosis",
    data=dados,
    palette="hls",
    legend=False
)

Comparação de variavies concave points_worst com diagnosis:
essa variavel possui uma correlação de 80% com nossa variavel target diagnosis, e somente 2 outlayers para cada valor de diagnosis
entendemos que vai ser uma variavel muito importante durante as analises.

In [4]:
sb.boxplot(
    x="diagnosis",
    y="concave points_worst",
    hue="diagnosis",
    data=dados,
    palette="hls",
    legend=False
)

Comparação de variavies perimeter_worst com diagnosis:
essa variavel possui uma correlação de 80% com nossa variavel target diagnosis, e somente 3 outlayers quando diagnosis=M e 2 quando diagnosis = B
essa variavel tambem ser muito importante durante as analises.

In [5]:
sb.boxplot(
    x="diagnosis",
    y="perimeter_worst",
    hue="diagnosis",
    data=dados,
    palette="hls",
    legend=False
)

Comparação de variavies radius_worst com diagnosis:
essa variavel possui uma correlação de 80% com nossa variavel target diagnosis, e somente 2 outlayers para cada valor de diagnosis
essa variavel tambem ser muito importante durante as analises.

In [6]:
sb.boxplot(
    x="diagnosis",
    y="radius_worst",
    hue="diagnosis",
    data=dados,
    palette="hls",
    legend=False
)

Para fins academicos, para tratar dados nulos, no nosso projeto isso não foi necessário pois não existe colunas com dados nulos

In [7]:
# função inplace nao recomendada para alterar dados direto na 
# na base de dados original
# dados["Unnamed"].fillna(value=0, inplace=True)

Abaixo uma forma gráfica de analisar os valores de uma certa variavel utilizando boxplot

In [8]:
sb.boxplot(x=dados["perimeter_worst"])

histplot - Exibe um grafico de barras com os dados da coluna em questão
entendemos que este grafico é melhor para visualizar os dados de uma variavel de forma mais precisa

In [9]:
sb.histplot(data=dados,x="perimeter_worst")

Grafico de swarmplot para visualizar o agrupamento dos dados e a correlação com a nossa variavel target
em seguida executamos o grafico para as nossas 4 principais variaveis
"concave points_mean","concave points_worst","perimeter_worst","radius_worst"
o resultado nos mostra um agrupamento visual entre M e B na nossa variavel target

In [10]:
sb.set_theme(style="whitegrid", palette="muted")
ax = sb.swarmplot(data=dados, x="diagnosis", y="concave points_mean", hue="diagnosis")
ax.set(ylabel="Radios")

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.5% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.7% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

[Text(243.22222222222223, 0.5, 'Radios')]

In [11]:
sb.set_theme(style="whitegrid", palette="muted")
ax = sb.swarmplot(data=dados, x="diagnosis", y="concave points_worst", hue="diagnosis")
ax.set(ylabel="Radios")

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.5% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.7% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

[Text(243.22222222222223, 0.5, 'Radios')]

In [12]:
sb.set_theme(style="whitegrid", palette="muted")
ax = sb.swarmplot(data=dados, x="diagnosis", y="perimeter_worst", hue="diagnosis")
ax.set(ylabel="Radios")

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.5% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.7% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 89.2% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 96.9% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

[Text(243.22222222222223, 0.5, 'Radios')]

In [13]:
sb.set_theme(style="whitegrid", palette="muted")
ax = sb.swarmplot(data=dados, x="diagnosis", y="radius_worst", hue="diagnosis")
ax.set(ylabel="Radios")

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.5% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.7% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 89.2% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 96.9% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 98.6% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

/home/lucas/.local/lib/python3.12/site-packages/seaborn/categorical.py:3399: UserWarning: 99.4% of the points cannot be placed; you may want to decrease the size of the markers or use stripplot.
  warnings.warn(msg, UserWarning)

[Text(243.22222222222223, 0.5, 'Radios')]

O grafico de violin nos mostra mais detalhes e os valores dos dados ao mover o cursor do mouse sobre a area plotada

In [14]:
import plotly_express as px

px.violin(dados,x="diagnosis",y="concave points_mean", color ="diagnosis",box=True, points="all")

In [15]:
px.violin(dados,x="diagnosis",y="concave points_worst", color ="diagnosis",box=True, points="all")

In [16]:
px.violin(dados,x="diagnosis",y="perimeter_worst", color ="diagnosis",box=True, points="all")

In [17]:
px.violin(dados,x="diagnosis",y="radius_worst", color ="diagnosis",box=True, points="all")

Neste ponto vamos tratar nossa variavel target diagnosis do tipo strig, transformar-la em numerico para ser entendida pelo modelo, para isso utilizamos o label encoder
M = 1 
B = 0

In [18]:
from sklearn.preprocessing import LabelEncoder
dados.head()
colunas = ["diagnosis"]

label_enconder = LabelEncoder()

for col in colunas:
    dados[col] = label_enconder.fit_transform(dados[col])
dados.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Importar biblioteca matplotlib.pyplot
analise do mapa de calor para entender a correlação entre as variaveis com diagnosis
segundo analise do grafico as variaveis concave points_mean","concave points_worst","perimeter_worst","radius_worst são as 4 com maior relação com a variavel target diagnosis, com 0,8

In [19]:
import  matplotlib.pyplot as plt

In [20]:
correlation_matriz = dados.corr().round(1)

fig, ax = plt.subplots(figsize=(20,20))
sb.heatmap(data=correlation_matriz,annot=True,linewidths=5,ax=ax )

criar variaveis para os modelos 
na primeira execução haviamos utilziado drop da coluna nula (Unnamed), porém após analise identificamos que a virgula extra estava causando o problema, então deixamos essa parte comentada no codigo e selecionamos as 4 principais variaveis com correlação de 80% na nossa variável target

In [21]:
x = dados[["concave points_mean","concave points_worst","perimeter_worst","radius_worst"]]
#x = dados.drop(columns=["Unnamed"])
y = dados["diagnosis"]

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

Serparar os dados entre treino e teste, sendo 70% para treinamento e 30% para testes

In [22]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42, stratify=y
)

In [23]:
print(x_test)

     concave points_mean  concave points_worst  perimeter_worst  radius_worst
448             0.029250               0.09594           108.10        16.300
346             0.008488               0.05093            86.54        13.640
568             0.000000               0.00000            59.16         9.456
411             0.024800               0.07431            79.93        12.410
519             0.029950               0.08045            93.63        14.450
..                   ...                   ...              ...           ...
74              0.022720               0.08660            89.71        14.110
39              0.054390               0.22580           107.30        15.530
99              0.058390               0.15650           109.50        16.330
115             0.020080               0.07247            87.54        13.670
219             0.066370               0.16250           180.20        27.900

[171 rows x 4 columns]

Padronização dos dados na mesma escala

In [24]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [25]:
scaler = StandardScaler()
scaler.fit(x_train)

x_train_escalonado = scaler.transform(x_train)
x_test_escalonado = scaler.transform(x_test)

importar biblioteca numpy

In [26]:
import numpy as np

Verificação do erro em K, analisando 10 "vizinhos"

In [27]:
error = []

for i in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train_escalonado, y_train)
    pred_i = knn.predict(x_test_escalonado)
    error.append(np.mean(pred_i != y_test))


plt.Figure(figsize=(12,6))
plt.plot(range(1,10),error,color="red",linestyle="dashed", marker="o",markerfacecolor="blue", markersize=10 )
plt.title("Erro medio para K")
plt.xlabel("Valor de K")
plt.ylabel("Erro Medio")

Text(215.64246961805554, 0.5, 'Erro Medio')

criar modelo classificados

In [28]:
modelo_classificador_knn = KNeighborsClassifier(n_neighbors=5)
modelo_classificador_knn.fit(x_train_escalonado,y_train)

y_predict_knn = modelo_classificador_knn.predict(x_test_escalonado)
y_predict_knn

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])

Avaliar a performance/acuracia do modelo KNN com os hiperparametros definidos manualmente.
Este resultado será utilizado como linha de base para comparação com a otimização por algoritmo genético.

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_predict_knn))

0.9298245614035088

Comparar a linha de base com o modelo SVM utilizando hiperparametros definidos manualmente.
Na sequencia o algoritmo genético buscará uma combinação de hiperparametros com melhor capacidade de generalização.

In [30]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

In [31]:
modelo_classificador_svm = Pipeline(
    [
        ("linear_svc",LinearSVC(C=1))
    ]
)

modelo_classificador_svm.fit(x_train_escalonado,y_train)

y_predict_svm = modelo_classificador_svm.predict(x_test_escalonado)

print(accuracy_score(y_test, y_predict_svm))

0.9649122807017544

Criar a linha de base do modelo Random Forest com os hiperparametros padrão da biblioteca.
O modelo otimizado será treinado depois da busca realizada pelo algoritmo genético.

In [32]:
from sklearn.ensemble import RandomForestClassifier # RandomForest

In [33]:
  # RandomForest
modelo_classificador_rf = RandomForestClassifier(random_state=7) 
modelo_classificador_rf.fit(x_train_escalonado, y_train) 
y_predict_rf = modelo_classificador_rf.predict(x_test_escalonado)
print(accuracy_score(y_test, y_predict_rf))

0.935672514619883

Registrar métricas da linha de base

Antes da otimização genética, as métricas de teste dos três modelos são armazenadas para comparação posterior (accuracy, precision, recall e F1).

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def calcular_metricas(y_real, y_pred):
    return {
        "accuracy": accuracy_score(y_real, y_pred),
        "precision": precision_score(y_real, y_pred, zero_division=0),
        "recall": recall_score(y_real, y_pred, zero_division=0),
        "f1": f1_score(y_real, y_pred, zero_division=0),
    }

metricas_baseline = {
    "KNN": calcular_metricas(y_test, y_predict_knn),
    "SVM": calcular_metricas(y_test, y_predict_svm),
    "Random Forest": calcular_metricas(y_test, y_predict_rf),
}

pd.DataFrame(metricas_baseline).T.round(4)

               accuracy  precision  recall      f1
KNN              0.9298     0.9643  0.8438  0.9000
SVM              0.9649     0.9677  0.9375  0.9524
Random Forest    0.9357     0.9344  0.8906  0.9120

Otimização dos hiperparametros utilizando Algoritmo Genético

Nesta etapa será implementado um algoritmo genético para buscar automaticamente os melhores hiperparametros dos modelos KNN, SVM e Random Forest.

Cada individuo da população representa uma combinação de hiperparametros. A qualidade de cada individuo é calculada com validação cruzada estratificada utilizando recall como função de fitness. Para este problema o recall é importante porque penaliza os casos positivos que o modelo classificou como negativos.

O processo utiliza seleção por torneio, crossover uniforme, mutação e elitismo. A semente permite reproduzir os mesmos resultados em novas execuções.

In [35]:
#Bibliotecas utilizadas pelo algoritmo genetico e pela validacao dos modelos
import random
from copy import deepcopy

import numpy as np
from sklearn.base import clone
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

#Semente utilizada para reproduzir a populacao inicial, cruzamentos e mutacoes
SEMENTE_AG = 42
random.seed(SEMENTE_AG)
np.random.seed(SEMENTE_AG)

Configuração do espaço de busca

O espaço de busca informa quais valores o algoritmo genético poderá testar para cada hiperparametro. Foram selecionados parametros compatíveis com os três classificadores já utilizados no projeto.

In [36]:
#Espaco de busca dos hiperparametros para cada modelo
espacos_busca = {
    "KNN": {
        "n_neighbors": list(range(1, 26, 2)),
        "weights": ["uniform", "distance"],
        "p": [1, 2]
    },
    "SVM": {
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
        "class_weight": [None, "balanced"],
        "max_iter": [2000, 5000, 10000]
    },
    "Random Forest": {
        "n_estimators": [100, 200, 300, 400, 500],
        "max_depth": [None, 3, 5, 8, 12, 16, 20],
        "min_samples_split": [2, 4, 6, 8, 10],
        "min_samples_leaf": [1, 2, 3, 4, 5],
        "max_features": ["sqrt", "log2", None],
        "class_weight": [None, "balanced"]
    }
}

#Fabricas dos modelos. Cada funcao recebe um dicionario de hiperparametros
def criar_knn(parametros):
    return KNeighborsClassifier(**parametros)


def criar_svm(parametros):
    return LinearSVC(random_state=SEMENTE_AG, **parametros)


def criar_random_forest(parametros):
    return RandomForestClassifier(
        random_state=SEMENTE_AG,
        n_jobs=-1,
        **parametros
    )

fabricas_modelos = {
    "KNN": criar_knn,
    "SVM": criar_svm,
    "Random Forest": criar_random_forest
}

Funções do Algoritmo Genético

As funções abaixo executam as etapas principais:

1. Criar a população inicial de forma aleatória.
2. Avaliar cada individuo por validação cruzada estratificada.
3. Selecionar os pais por torneio.
4. Combinar os genes dos pais utilizando crossover uniforme.
5. Aplicar mutações para manter diversidade na população.
6. Preservar os melhores individuos por elitismo.

In [37]:
def criar_individuo(espaco_busca):
    """Cria uma combinacao aleatoria de hiperparametros."""
    return {
        parametro: random.choice(valores)
        for parametro, valores in espaco_busca.items()
    }


def criar_populacao(espaco_busca, tamanho_populacao):
    """Cria a populacao inicial do algoritmo genetico."""
    return [
        criar_individuo(espaco_busca)
        for _ in range(tamanho_populacao)
    ]


def chave_individuo(individuo):
    """Transforma o individuo em uma chave para reutilizar avaliacoes anteriores."""
    return tuple(sorted(individuo.items()))


def avaliar_individuo(individuo, fabrica_modelo, x_treino, y_treino, validacao, cache):
    """Calcula o recall medio do individuo utilizando validacao cruzada."""
    chave = chave_individuo(individuo)

    if chave not in cache:
        modelo = fabrica_modelo(individuo)
        resultados = cross_val_score(
            modelo,
            x_treino,
            y_treino,
            cv=validacao,
            scoring="recall",
            n_jobs=-1,
            error_score="raise"
        )
        cache[chave] = resultados.mean()

    return cache[chave]


def selecionar_por_torneio(populacao_avaliada, tamanho_torneio):
    """Seleciona o melhor individuo de uma amostra aleatoria da populacao."""
    competidores = random.sample(
        populacao_avaliada,
        k=min(tamanho_torneio, len(populacao_avaliada))
    )
    vencedor = max(competidores, key=lambda item: item[1])
    return deepcopy(vencedor[0])


def aplicar_crossover(pai_1, pai_2, taxa_crossover):
    """Combina os hiperparametros dos pais utilizando crossover uniforme."""
    if random.random() >= taxa_crossover:
        return deepcopy(pai_1), deepcopy(pai_2)

    filho_1 = {}
    filho_2 = {}

    for parametro in pai_1:
        if random.random() < 0.5:
            filho_1[parametro] = pai_1[parametro]
            filho_2[parametro] = pai_2[parametro]
        else:
            filho_1[parametro] = pai_2[parametro]
            filho_2[parametro] = pai_1[parametro]

    return filho_1, filho_2


def aplicar_mutacao(individuo, espaco_busca, taxa_mutacao):
    """Altera genes do individuo de acordo com a taxa de mutacao."""
    individuo_mutado = deepcopy(individuo)

    for parametro, valores in espaco_busca.items():
        if random.random() < taxa_mutacao:
            individuo_mutado[parametro] = random.choice(valores)

    return individuo_mutado


def executar_algoritmo_genetico(
    fabrica_modelo,
    espaco_busca,
    x_treino,
    y_treino,
    tamanho_populacao=50,
    numero_geracoes=8,
    taxa_crossover=0.8,
    taxa_mutacao=0.15,
    tamanho_torneio=3,
    quantidade_elites=2,
    verbose=True
):
    """Executa a busca genetica e retorna o melhor individuo encontrado."""
    validacao = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=SEMENTE_AG
    )
    cache_avaliacoes = {}
    populacao = criar_populacao(espaco_busca, tamanho_populacao)
    historico = []

    for geracao in range(1, numero_geracoes + 1):
        populacao_avaliada = [
            (
                individuo,
                avaliar_individuo(
                    individuo,
                    fabrica_modelo,
                    x_treino,
                    y_treino,
                    validacao,
                    cache_avaliacoes
                )
            )
            for individuo in populacao
        ]
        populacao_avaliada.sort(key=lambda item: item[1], reverse=True)

        melhor_individuo, melhor_fitness = populacao_avaliada[0]
        fitness_medio = np.mean([fitness for _, fitness in populacao_avaliada])
        historico.append({
            "geracao": geracao,
            "melhor_fitness": melhor_fitness,
            "fitness_medio": fitness_medio
        })

        if verbose:
            print(
                f"Geracao {geracao:02d} | "
                f"Melhor recall: {melhor_fitness:.4f} | "
                f"Recall medio: {fitness_medio:.4f}"
            )

        #Elitismo: preserva as melhores solucoes sem alteracao
        nova_populacao = [
            deepcopy(individuo)
            for individuo, _ in populacao_avaliada[:quantidade_elites]
        ]

        while len(nova_populacao) < tamanho_populacao:
            pai_1 = selecionar_por_torneio(populacao_avaliada, tamanho_torneio)
            pai_2 = selecionar_por_torneio(populacao_avaliada, tamanho_torneio)

            filho_1, filho_2 = aplicar_crossover(
                pai_1,
                pai_2,
                taxa_crossover
            )
            filho_1 = aplicar_mutacao(filho_1, espaco_busca, taxa_mutacao)
            filho_2 = aplicar_mutacao(filho_2, espaco_busca, taxa_mutacao)

            nova_populacao.extend([filho_1, filho_2])

        populacao = nova_populacao[:tamanho_populacao]

    #Realiza a avaliacao final porque a ultima populacao foi criada no fim do ciclo anterior
    populacao_final = [
        (
            individuo,
            avaliar_individuo(
                individuo,
                fabrica_modelo,
                x_treino,
                y_treino,
                validacao,
                cache_avaliacoes
            )
        )
        for individuo in populacao
    ]
    melhor_individuo, melhor_fitness = max(
        populacao_final,
        key=lambda item: item[1]
    )

    return deepcopy(melhor_individuo), melhor_fitness, historico

Experimentos com diferentes configurações do Algoritmo Genético

O Tech Challenge exige ao menos **3 experimentos** variando parâmetros do AG (população, mutação, etc.).

| Experimento | População | Gerações | Mutação | Cruzamento | Objetivo |
|-------------|-----------|----------|---------|------------|----------|
| Conservador | 8 | 10 | 0.05 | 0.70 | Baixa diversidade |
| Equilibrado | 12 | 10 | 0.15 | 0.80 | Equilíbrio exploração/explotação |
| Exploratório | 20 | 10 | 0.30 | 0.90 | Alta diversidade |

Os três experimentos comparam o recall de validação no **SVM**. Em seguida, a melhor configuração otimiza KNN, SVM e Random Forest.

In [38]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd()))
from algoritmo_genetico import EXPERIMENTOS_AG

# --- Experimento 1, 2 e 3: comparar configs do AG no SVM ---
resultados_experimentos = []

for experimento in EXPERIMENTOS_AG:
    print(f"\n=== Experimento: {experimento['nome']} ===")
    print(experimento["descricao"])

    params = {
        k: v for k, v in experimento.items()
        if k not in {"nome", "descricao"}
    }

    melhores_parametros, melhor_recall_cv, historico = executar_algoritmo_genetico(
        fabrica_modelo=fabricas_modelos["SVM"],
        espaco_busca=espacos_busca["SVM"],
        x_treino=x_train_escalonado,
        y_treino=y_train,
        verbose=True,
        **params,
    )

    resultados_experimentos.append({
        "experimento": experimento["nome"],
        "tamanho_populacao": experimento["tamanho_populacao"],
        "numero_geracoes": experimento["numero_geracoes"],
        "taxa_mutacao": experimento["taxa_mutacao"],
        "taxa_crossover": experimento["taxa_crossover"],
        "melhor_recall_cv": melhor_recall_cv,
        "melhores_parametros": melhores_parametros,
        "historico": historico,
        "config": params,
    })

    print("Melhores hiperparametros:", melhores_parametros)
    print(f"Melhor recall CV: {melhor_recall_cv:.4f}")

comparativo_experimentos = pd.DataFrame([
    {
        "experimento": r["experimento"],
        "populacao": r["tamanho_populacao"],
        "geracoes": r["numero_geracoes"],
        "mutacao": r["taxa_mutacao"],
        "crossover": r["taxa_crossover"],
        "melhor_recall_cv": r["melhor_recall_cv"],
    }
    for r in resultados_experimentos
]).sort_values("melhor_recall_cv", ascending=False)

print("\nComparativo dos 3 experimentos:")
try:
    display(comparativo_experimentos)
except NameError:
    print(comparativo_experimentos.to_string())

melhor_experimento = max(resultados_experimentos, key=lambda item: item["melhor_recall_cv"])
print(
    f"\nConfiguração vencedora: {melhor_experimento['experimento']} "
    f"(recall CV={melhor_experimento['melhor_recall_cv']:.4f})"
)

# --- Otimização final dos 3 modelos com a config vencedora ---
configuracao_ag = {
    **melhor_experimento["config"],
    "numero_geracoes": max(melhor_experimento["config"]["numero_geracoes"], 20),
    "verbose": True,
}

resultados_ag = {}

for nome_modelo in ["KNN", "SVM", "Random Forest"]:
    print(f"\nOtimizando o modelo {nome_modelo} com config {melhor_experimento['experimento']}")

    melhores_parametros, melhor_recall_cv, historico = executar_algoritmo_genetico(
        fabrica_modelo=fabricas_modelos[nome_modelo],
        espaco_busca=espacos_busca[nome_modelo],
        x_treino=x_train_escalonado,
        y_treino=y_train,
        **configuracao_ag,
    )

    resultados_ag[nome_modelo] = {
        "melhores_parametros": melhores_parametros,
        "melhor_recall_cv": melhor_recall_cv,
        "historico": historico,
        "experimento_base": melhor_experimento["experimento"],
    }

    print("Melhores hiperparametros:", melhores_parametros)
    print(f"Melhor recall medio na validacao cruzada: {melhor_recall_cv:.4f}")

=== Experimento: Conservador ===
População menor, poucas gerações e baixa mutação (explora pouco).

Geracao 01 | Melhor recall: 0.9389 | Recall medio: 0.9062
Geracao 02 | Melhor recall: 0.9389 | Recall medio: 0.9182
Geracao 03 | Melhor recall: 0.9389 | Recall medio: 0.9234
Geracao 04 | Melhor recall: 0.9389 | Recall medio: 0.9336
Geracao 05 | Melhor recall: 0.9389 | Recall medio: 0.9388
Geracao 06 | Melhor recall: 0.9453 | Recall medio: 0.9397
Geracao 07 | Melhor recall: 0.9453 | Recall medio: 0.9421
Geracao 08 | Melhor recall: 0.9453 | Recall medio: 0.9445
Geracao 09 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 10 | Melhor recall: 0.9453 | Recall medio: 0.9453
Melhores hiperparametros: {'C': 1, 'class_weight': 'balanced', 'max_iter': 2000}
Melhor recall CV: 0.9453

=== Experimento: Equilibrado ===
Configuração intermediária entre exploração e explotação.
Geracao 01 | Melhor recall: 0.9453 | Recall medio: 0.9296
Geracao 02 | Melhor recall: 0.9453 | Recall medio: 0.9404
Geracao 03 | Melhor recall: 0.9453 | Recall medio: 0.9415

Geracao 04 | Melhor recall: 0.9453 | Recall medio: 0.9403
Geracao 05 | Melhor recall: 0.9453 | Recall medio: 0.9448
Geracao 06 | Melhor recall: 0.9453 | Recall medio: 0.9385
Geracao 07 | Melhor recall: 0.9453 | Recall medio: 0.9447
Geracao 08 | Melhor recall: 0.9453 | Recall medio: 0.9385
Geracao 09 | Melhor recall: 0.9453 | Recall medio: 0.9447
Geracao 10 | Melhor recall: 0.9453 | Recall medio: 0.9408
Melhores hiperparametros: {'C': 1, 'class_weight': 'balanced', 'max_iter': 2000}
Melhor recall CV: 0.9453

=== Experimento: Exploratorio ===
População maior e mutação alta para diversificar a busca.

Geracao 01 | Melhor recall: 0.9453 | Recall medio: 0.9199
Geracao 02 | Melhor recall: 0.9453 | Recall medio: 0.9288
Geracao 03 | Melhor recall: 0.9453 | Recall medio: 0.9369
Geracao 04 | Melhor recall: 0.9453 | Recall medio: 0.9379
Geracao 05 | Melhor recall: 0.9453 | Recall medio: 0.9386
Geracao 06 | Melhor recall: 0.9453 | Recall medio: 0.9392
Geracao 07 | Melhor recall: 0.9453 | Recall medio: 0.9402
Geracao 08 | Melhor recall: 0.9453 | Recall medio: 0.9382

Geracao 09 | Melhor recall: 0.9453 | Recall medio: 0.9389
Geracao 10 | Melhor recall: 0.9453 | Recall medio: 0.9392
Melhores hiperparametros: {'C': 1, 'class_weight': 'balanced', 'max_iter': 2000}
Melhor recall CV: 0.9453

Comparativo dos 3 experimentos:

    experimento  populacao  geracoes  mutacao  crossover  melhor_recall_cv
0   Conservador          8        10     0.05        0.7          0.945287
1   Equilibrado         12        10     0.15        0.8          0.945287
2  Exploratorio         20        10     0.30        0.9          0.945287

Configuração vencedora: Conservador (recall CV=0.9453)

Otimizando o modelo KNN com config Conservador
Geracao 01 | Melhor recall: 0.8844 | Recall medio: 0.8751

Geracao 02 | Melhor recall: 0.8979 | Recall medio: 0.8861
Geracao 03 | Melhor recall: 0.8979 | Recall medio: 0.8912
Geracao 04 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 05 | Melhor recall: 0.8979 | Recall medio: 0.8962

Geracao 06 | Melhor recall: 0.8979 | Recall medio: 0.8911
Geracao 07 | Melhor recall: 0.8979 | Recall medio: 0.8962
Geracao 08 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 09 | Melhor recall: 0.8979 | Recall medio: 0.8962
Geracao 10 | Melhor recall: 0.8979 | Recall medio: 0.8928
Geracao 11 | Melhor recall: 0.8979 | Recall medio: 0.8945
Geracao 12 | Melhor recall: 0.8979 | Recall medio: 0.8962
Geracao 13 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 14 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 15 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 16 | Melhor recall: 0.8979 | Recall medio: 0.8946
Geracao 17 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 18 | Melhor recall: 0.8979 | Recall medio: 0.8954
Geracao 19 | Melhor recall: 0.8979 | Recall medio: 0.8979
Geracao 20 | Melhor recall: 0.8979 | Recall medio: 0.8979
Melhores hiperparametros: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}
Melhor recall medio na validacao cruzada: 0.8979

Otimizando o modelo SVM com config Conservador
Geracao 01 | Melhor recall: 0.9453 | Recall medio: 0.9199

Geracao 02 | Melhor recall: 0.9453 | Recall medio: 0.9301
Geracao 03 | Melhor recall: 0.9453 | Recall medio: 0.9378
Geracao 04 | Melhor recall: 0.9453 | Recall medio: 0.9445
Geracao 05 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 06 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 07 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 08 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 09 | Melhor recall: 0.9453 | Recall medio: 0.9402
Geracao 10 | Melhor recall: 0.9453 | Recall medio: 0.9453

Geracao 11 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 12 | Melhor recall: 0.9453 | Recall medio: 0.9445
Geracao 13 | Melhor recall: 0.9453 | Recall medio: 0.9402
Geracao 14 | Melhor recall: 0.9453 | Recall medio: 0.9445
Geracao 15 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 16 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 17 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 18 | Melhor recall: 0.9453 | Recall medio: 0.9453
Geracao 19 | Melhor recall: 0.9453 | Recall medio: 0.9402
Geracao 20 | Melhor recall: 0.9453 | Recall medio: 0.9453
Melhores hiperparametros: {'C': 1, 'class_weight': 'balanced', 'max_iter': 2000}
Melhor recall medio na validacao cruzada: 0.9453

Otimizando o modelo Random Forest com config Conservador

Geracao 01 | Melhor recall: 0.9179 | Recall medio: 0.9154

Geracao 02 | Melhor recall: 0.9179 | Recall medio: 0.9171

Geracao 03 | Melhor recall: 0.9246 | Recall medio: 0.9188

Geracao 04 | Melhor recall: 0.9246 | Recall medio: 0.9196
Geracao 05 | Melhor recall: 0.9246 | Recall medio: 0.9238

Geracao 06 | Melhor recall: 0.9246 | Recall medio: 0.9238

Geracao 07 | Melhor recall: 0.9246 | Recall medio: 0.9246

Geracao 08 | Melhor recall: 0.9246 | Recall medio: 0.9229

Geracao 09 | Melhor recall: 0.9246 | Recall medio: 0.9238

Geracao 10 | Melhor recall: 0.9246 | Recall medio: 0.9221
Geracao 11 | Melhor recall: 0.9246 | Recall medio: 0.9238

Geracao 12 | Melhor recall: 0.9246 | Recall medio: 0.9204

Geracao 13 | Melhor recall: 0.9246 | Recall medio: 0.9229

Geracao 14 | Melhor recall: 0.9246 | Recall medio: 0.9221

Geracao 15 | Melhor recall: 0.9246 | Recall medio: 0.9221
Geracao 16 | Melhor recall: 0.9246 | Recall medio: 0.9229

Geracao 17 | Melhor recall: 0.9246 | Recall medio: 0.9238
Geracao 18 | Melhor recall: 0.9246 | Recall medio: 0.9246
Geracao 19 | Melhor recall: 0.9246 | Recall medio: 0.9246
Geracao 20 | Melhor recall: 0.9246 | Recall medio: 0.9246

Melhores hiperparametros: {'n_estimators': 500, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'class_weight': 'balanced'}
Melhor recall medio na validacao cruzada: 0.9246

Treinar os modelos com os melhores hiperparametros

Após a busca, cada modelo é recriado com a melhor combinação encontrada, treinado com todo o conjunto de treinamento e utilizado para gerar as previsões do conjunto de teste. As variáveis já existentes no notebook são atualizadas para que as análises de matriz de confusão, relatório de classificação e curva ROC utilizem os modelos otimizados.

In [39]:
#Criar e treinar os modelos otimizados
modelo_classificador_knn = criar_knn(
    resultados_ag["KNN"]["melhores_parametros"]
)
modelo_classificador_svm = criar_svm(
    resultados_ag["SVM"]["melhores_parametros"]
)
modelo_classificador_rf = criar_random_forest(
    resultados_ag["Random Forest"]["melhores_parametros"]
)

modelo_classificador_knn.fit(x_train_escalonado, y_train)
modelo_classificador_svm.fit(x_train_escalonado, y_train)
modelo_classificador_rf.fit(x_train_escalonado, y_train)

#Gerar novas predicoes para as metricas apresentadas nas proximas etapas
y_predict_knn = modelo_classificador_knn.predict(x_test_escalonado)
y_predict_svm = modelo_classificador_svm.predict(x_test_escalonado)
y_predict_rf = modelo_classificador_rf.predict(x_test_escalonado)

print("Acuracia KNN otimizado:", accuracy_score(y_test, y_predict_knn))
print("Acuracia SVM otimizado:", accuracy_score(y_test, y_predict_svm))
print("Acuracia Random Forest otimizado:", accuracy_score(y_test, y_predict_rf))

Acuracia KNN otimizado: 0.9239766081871345
Acuracia SVM otimizado: 0.9590643274853801
Acuracia Random Forest otimizado: 0.9473684210526315

Comparativo baseline × modelos otimizados

Tabela com accuracy, precision, recall e F1 no conjunto de teste, antes e depois do algoritmo genético.

In [40]:
metricas_otimizadas = {
    "KNN": calcular_metricas(y_test, y_predict_knn),
    "SVM": calcular_metricas(y_test, y_predict_svm),
    "Random Forest": calcular_metricas(y_test, y_predict_rf),
}

linhas = []
for modelo in ["KNN", "SVM", "Random Forest"]:
    base = metricas_baseline[modelo]
    otim = metricas_otimizadas[modelo]
    for metrica in ["accuracy", "precision", "recall", "f1"]:
        linhas.append({
            "modelo": modelo,
            "metrica": metrica,
            "baseline": base[metrica],
            "otimizado_ag": otim[metrica],
            "ganho": otim[metrica] - base[metrica],
        })

comparativo_baseline_vs_ag = pd.DataFrame(linhas)
try:
    display(comparativo_baseline_vs_ag.round(4))
except NameError:
    print(comparativo_baseline_vs_ag.round(4).to_string())

resumo_pivot = comparativo_baseline_vs_ag.pivot_table(
    index="modelo",
    columns="metrica",
    values=["baseline", "otimizado_ag", "ganho"],
)
try:
    display(resumo_pivot.round(4))
except NameError:
    print(resumo_pivot.round(4).to_string())

           modelo    metrica  baseline  otimizado_ag   ganho
0             KNN   accuracy    0.9298        0.9240 -0.0058
1             KNN  precision    0.9643        0.9322 -0.0321
2             KNN     recall    0.8438        0.8594  0.0156
3             KNN         f1    0.9000        0.8943 -0.0057
4             SVM   accuracy    0.9649        0.9591 -0.0058
5             SVM  precision    0.9677        0.9385 -0.0293
6             SVM     recall    0.9375        0.9531  0.0156
7             SVM         f1    0.9524        0.9457 -0.0066
8   Random Forest   accuracy    0.9357        0.9474  0.0117
9   Random Forest  precision    0.9344        0.9365  0.0021
10  Random Forest     recall    0.8906        0.9219  0.0312
11  Random Forest         f1    0.9120        0.9291  0.0171

              baseline                              ganho                    \
metrica       accuracy      f1 precision  recall accuracy      f1 precision
modelo
KNN             0.9298  0.9000    0.9643  0.8438  -0.0058 -0.0057   -0.0321
Random Forest   0.9357  0.9120    0.9344  0.8906   0.0117  0.0171    0.0021
SVM             0.9649  0.9524    0.9677  0.9375  -0.0058 -0.0066   -0.0293

                      otimizado_ag
metrica        recall     accuracy      f1 precision  recall
modelo
KNN            0.0156       0.9240  0.8943    0.9322  0.8594
Random Forest  0.0312       0.9474  0.9291    0.9365  0.9219
SVM            0.0156       0.9591  0.9457    0.9385  0.9531

Visualização da evolução do Algoritmo Genético

O gráfico compara o melhor recall e o recall médio da população ao longo das gerações. A diferença entre as curvas ajuda a observar a evolução da busca e a convergência da população.

In [41]:
#Exibir a evolucao do fitness de cada modelo durante as geracoes
fig, eixos = plt.subplots(1, 3, figsize=(18, 5))

for eixo, nome_modelo in zip(eixos, ["KNN", "SVM", "Random Forest"]):
    historico = pd.DataFrame(resultados_ag[nome_modelo]["historico"])

    eixo.plot(
        historico["geracao"],
        historico["melhor_fitness"],
        marker="o",
        label="Melhor recall"
    )
    eixo.plot(
        historico["geracao"],
        historico["fitness_medio"],
        marker="s",
        label="Recall medio"
    )
    eixo.set_title(nome_modelo)
    eixo.set_xlabel("Geracao")
    eixo.set_ylabel("Recall")
    eixo.set_ylim(0, 1.05)
    eixo.grid(alpha=0.3)
    eixo.legend()

plt.tight_layout()
plt.show()

/tmp/ipykernel_69048/3315928258.py:27: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Resumo dos hiperparametros encontrados

A tabela abaixo consolida o melhor recall obtido na validação cruzada e os hiperparametros selecionados pelo algoritmo genético para cada modelo.

In [42]:
#Consolidar os resultados encontrados pelo algoritmo genetico
resumo_ag = pd.DataFrame([
    {
        "modelo": nome_modelo,
        "melhor_recall_cv": resultado["melhor_recall_cv"],
        "melhores_parametros": resultado["melhores_parametros"]
    }
    for nome_modelo, resultado in resultados_ag.items()
])

resumo_ag

,modelo,melhor_recall_cv,melhores_parametros
0,KNN,0.897931,"{'n_neighbors': 1, 'weights': 'uniform', 'p': 2}"
1,SVM,0.945287,"{'C': 1, 'class_weight': 'balanced', 'max_iter..."
2,Random Forest,0.924598,"{'n_estimators': 500, 'max_depth': 20, 'min_sa..."

Entendemos que para um algoritimo que preve possibilidade de uma pessoa possuir um tumor é muito mais imoportante prever como falso posivivo do que falso negativo, porque embora a informação de tumor vai causar um impacto emocional na pessoa ela terá oportunidade de fazer mais exames e comprovar que está saudadel, o inverso pode resultar na falta de tratamento e investigação e a pessoa pode não ter tempo habil para se tratar quando a doença evoluir
abaixo nossas analises das metricas

In [43]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

Analisando os resultados, mapa de calor

para o modelo KNN 
falso verdadeiro: 10
falso negativo: 2

In [44]:
matriz_confusao = confusion_matrix(y_test, y_predict_knn)
plt.figure(figsize = (8, 4))
sb.heatmap(matriz_confusao, annot = True, fmt="d",cmap = "Blues")
plt.xlabel("Predição");
plt.ylabel("Dados Reais");

para o modelo SVM
falso verdadeiro: 4
falso negativo: 2

In [45]:
matriz_confusao = confusion_matrix(y_test, y_predict_svm)
plt.figure(figsize = (8, 4))
sb.heatmap(matriz_confusao, annot = True, fmt="d",cmap = "Blues")
plt.xlabel("Predição");
plt.ylabel("Dados Reais");

Para o modelo Random Forest
falso verdadeiro: 7
falso negativo: 4

In [46]:
matriz_confusao = confusion_matrix(y_test, y_predict_rf)
plt.figure(figsize = (8, 4))
sb.heatmap(matriz_confusao, annot = True, fmt="d",cmap = "Blues")
plt.xlabel("Predição");
plt.ylabel("Dados Reais");

Conclusão
Para o cenario de predição de laudos de cancer o melhor modelo foi o SVM pois errou somente 2 casos de falso negativo
falso verdadeiro: 4
falso negativo: 2

In [47]:
from sklearn.metrics import classification_report #métricas de avaliação

Comparando com as metricas, se comprova que SVM teve melhor performance pricipalmente comparando com a metrica precision

In [48]:
print(classification_report(y_test, y_predict_knn))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94       107
           1       0.93      0.86      0.89        64

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171

In [49]:
print(classification_report(y_test, y_predict_svm))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       107
           1       0.94      0.95      0.95        64

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

In [50]:
print(classification_report(y_test, y_predict_rf))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       107
           1       0.94      0.92      0.93        64

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171

Utilizando a curva ROC e AUC para validar a sensibildade do modelo

In [51]:
from sklearn import metrics
from sklearn.metrics import roc_curve, auc

Testando o ROC para o modelo KNN

In [52]:
y_prob_knn = modelo_classificador_knn.predict_proba(x_test_escalonado)[:,1] 
false_positive_rate_knn, true_positive_rate_knn, thresholds_knn = roc_curve(y_test, y_prob_knn)
roc_auc_knn = auc(false_positive_rate_knn, true_positive_rate_knn)
roc_auc_knn

0.9109959112149533

In [53]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate_knn,true_positive_rate_knn, color='red',label = 'AUC = %0.2f' % roc_auc_knn)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')

Text(0.5, 0, 'False Positive Rate')

Testando o ROC para o modelo SVM
Conclusão: após rodar o ROC e AUC para os tres modelos, o modelo SVM possui a melhor sensibilidade

In [54]:
y_prob_svm = modelo_classificador_svm.decision_function(x_test_escalonado)
false_positive_rate_svm, true_positive_rate_svm, thresholds_svm = roc_curve(y_test, y_prob_svm)
roc_auc_svm = auc(false_positive_rate_svm, true_positive_rate_svm)
roc_auc_svm

0.9967873831775701

In [55]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate_svm,true_positive_rate_svm, color='red',label = 'AUC = %0.2f' % roc_auc_svm)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')

Text(0.5, 0, 'False Positive Rate')

Testando o ROC para o modelo RF

In [56]:
y_prob_rf = modelo_classificador_rf.predict_proba(x_test_escalonado)[:,1] 
false_positive_rate_rf, true_positive_rate_rf, thresholds_rf = roc_curve(y_test, y_prob_rf)
roc_auc_rf = auc(false_positive_rate_rf, true_positive_rate_rf)
roc_auc_rf

0.9878796728971962

In [57]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate_rf,true_positive_rate_rf, color='red',label = 'AUC = %0.2f' % roc_auc_rf)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')

Text(0.5, 0, 'False Positive Rate')

Conclusão final:
De acordo com as métricas disponiveis até o momento, para o nosso projeto o modelo que melhor prevê se uma pessoa tem ou não um tumor é o modelo SVM, possui uma taxa de acuracia de 96% o que é considerado excelente.
Nosso projeto auxilia o profissional de saude a identificar a doença, porém o profissional é quem realmente esta de fato qualificado a fornecer o laudo final ao paciente.

Salvar o modelo treinado

In [58]:
import pickle
filename = 'modelo_pipeline_genetico.pkl'

pickle.dump(modelo_classificador_svm, open(filename, 'wb'))

print(f"Pipeline exported to {filename}")

Pipeline exported to modelo_pipeline_genetico.pkl

Para carregar o modelo e fazer predições

In [59]:
import pickle
modelo_salvo = pickle.load(open("modelo_pipeline_genetico.pkl","rb"))
modelo_salvo.predict(x_test_escalonado)

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])